### ISSUE TITLE
Is there anyone have the example file for testing the setup?

### ISSUE THREAD

**Issue by hzung** [DaWelter/h264decoder#11]
Is there anyone who has the example file mentioned in the [example code](https://github.com/DaWelter/h264decoder/blob/master/readme.md)?

I just want this file to run the demo code to make sure that my setup is correct.

```
...
f = open(thefile, 'rb')
...
```

Thank you all,

**Comment by DaWelter** [comment]
Hi

I haven't published an example file. The name is just a placeholder.
You'd have to capture one by yourself with raspivid. Or maybe you can extract the raw h264 data from a container format. I can't help with the latter though.

best regards

**Comment by DaWelter** [comment]
Now I have test files in the test/ folder .. and tests
