### ISSUE TITLE
Support for hardware accelerated video decoding

### ISSUE THREAD

**Issue by idkosilov** [DaWelter/h264decoder#12]
Hi, does h264decoder support hardware acceleration (opencl, cuda, vaapi). If not, is it planned to implement this feature in the future?

**Comment by DaWelter** [comment]
Hi,

tbh I don't know. But I guess not. It seems there are a few more steps required as I found in this blog https://habr.com/en/company/intel/blog/575632/.

It is also not planned. But if someone wants to add it, be my guest :-)
