### ISSUE TITLE
support h264decoder for python3 and macOS

### ISSUE THREAD

**Issue by rdarmoul** [DaWelter/h264decoder#4]
hi together, 

I love your decoder since this one really works with python2 and devices like the Tello drone. 
Unluckily, python2 is not supported anymore :(
your decoder is really awesome, I would love to get a current version for python3

**Comment by f41ardu** [comment]
Have a look into my fork. Based on Dawelters development branch (broken on my Raspberry) I made y version working for python3 (Raspberry only). There is still a wrong cmake instruction im my fork, stay tuned I'll update in a few hours.

**Comment by DaWelter** [comment]
I hope you don't have to use Python 2 anymore. Build & installl should be easier now.
